spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/Health
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  elasticsearch:
    username: elastic
    password: lf1F4MF1+G2jLZTJLvWW
    ssl: 38adca41d2966aba6cf57b2f8f2bda331929829b04bc8c4ffc959d943692c494
    uris:
      - localhost:9200

  data:
    elasticsearch:
      repositories:
        enabled: true

    redis:
      host: localhost
      port: 6379
      username:
      password:



jwt:
  secret: fjkdhnfaskjlhflasdfjgiodsfhglkhdfgkjbhdlfugbndkfjlbgdksujbglasbfgkjsdabjkhbg
  expire-ms: 3600000

public-data:
  url: https://apis.data.go.kr/1471000/FoodNtrCpntDbInfo/getFoodNtrCpntDbInq
  key: Y5LtLLSt92cEIrjBX%2BczFOpNqQ8QKJw%2F8QymE51tsgoP5n4g3MKBPHJmgyqpNt0zTHu3tiaQE80Lx%2FX28cXDzw%3D%3D
