spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/Health
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: fjkdhnfaskjlhflasdfjgiodsfhglkhdfgkjbhdlfugbndkfjlbgdksujbglasbfgkjsdabjkhbg
  expire-ms: 3600000
