### mypage 마이페이지
GET localhost:8080/naver_s6l2d3WzMpsNC5LDfilFIYmqepWMAvwEa5THTVL6kEQ/mypage
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJhdXRoSWQiOiJuYXZlcl9zNmwyZDNXek1wc05DNUxEZmlsRklZbXFlcFdNQXZ3RWE1VEhUVkw2a0VRIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcxOTEzODE2NSwiZXhwIjoxNzE5MTQxNzY1fQ.bzi5sWbaD6zWIa3NmDgY-yha3X2gU6lCdQzc_vl852c


### 유저 정보 수정
PATCH localhost:8080/naver_s6l2d3WzMpsNC5LDfilFIYmqepWMAvwEa5THTVL6kEQ/mypage/userinfo
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJhdXRoSWQiOiJuYXZlcl9zNmwyZDNXek1wc05DNUxEZmlsRklZbXFlcFdNQXZ3RWE1VEhUVkw2a0VRIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcxOTEzODE2NSwiZXhwIjoxNzE5MTQxNzY1fQ.bzi5sWbaD6zWIa3NmDgY-yha3X2gU6lCdQzc_vl852c
Content-Type: application/json

{
  "height": 123,
  "weight": 456,
  "goalWeight": 789
}


### 닉네임 정보 수정
PATCH localhost:8080/naver_s6l2d3WzMpsNC5LDfilFIYmqepWMAvwEa5THTVL6kEQ/mypage/nickname
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJhdXRoSWQiOiJuYXZlcl9zNmwyZDNXek1wc05DNUxEZmlsRklZbXFlcFdNQXZ3RWE1VEhUVkw2a0VRIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcxOTEzODE2NSwiZXhwIjoxNzE5MTQxNzY1fQ.bzi5sWbaD6zWIa3NmDgY-yha3X2gU6lCdQzc_vl852c
Content-Type: application/json

{
  "nickname": "수정닉네임1"
}